### ISSUE TITLE
Error in expression

### ISSUE THREAD

**Issue by MAJThomasASOT** [diwako/diwako_cbrn#2]
This error shown below, occurs when playing in both multiplayer and singleplayer editor. The log from below is from a dedi server log which is occurring approx 5 times per second.  

if (_this isEqualTypeArray [[], 0, 0, 0, false]) e>
20:39:06   Error position: <isEqualTypeArray [[], 0, 0, 0, false]) e>
20:39:06   Error isequaltypearray: Type Object, expected Array
20:39:06 File A3\functions_f\Misc\fn_getArea.sqf [BIS_fnc_getArea]..., line 30
20:39:06 Error in expression <s, rectangular _this, -1]};

Any ideas?

**Comment by diwako** [comment]
Hey, this script does not use `BIS_fnc_getArea` at all. Just to be on the safe side, try the script in an empty mission, such as the example mission.

If the error is still happening reduce the amount of mods to just cba + ace.

**Comment by MAJThomasASOT** [comment]
Error not linked to this mod/script. 

Removing my issue. Thanks Diwako for quickly helping me.
